# Generated by Django 2.2 on 2020-06-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tclone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
